### ISSUE TITLE
How to get rid of initials?

### ISSUE THREAD

**Issue by theschles** [connie-clark/print-trello#1]
Hi there,

I just discovered print-trello.  Thank you for a great utility!

I'm having one issue -- how do I get rid of the initials?

![image](https://user-images.githubusercontent.com/901430/31055727-19fa9810-a67c-11e7-8337-2e604d592aae.png)

Here are my card settings:

![image](https://user-images.githubusercontent.com/901430/31055732-2f27da4a-a67c-11e7-9715-ba852c46e293.png)

Note that "show card creator" is disabled.

FYI I'm using Slimjet version 15.1.4.0 (based on Chromium 59.0.3071.86 (64-bit)) on macOS Sierra.

Thank you for your help and keep up the good work!

**Comment by connie-clark** [comment]
This is a bug -- two different ways (a) it should offer a 'don't show' option, and (b) the preference is not being checked :-(

Will try to get to this this week.

**Comment by connie-clark** [comment]
Bug has been fixed - can now select 'do-not-show' as preference where people would normally be shown.
