### ISSUE TITLE
Print preferences don't work

### ISSUE THREAD

**Issue by moveair** [connie-clark/print-trello#3]
I am having trouble with the preference saving feature. 

It asks me to check that I have " marks around the nickname which I do but still doesn't work for me.

Otherwise this is the best tool.

Screenshots added

![screen shot 2017-11-01 at 11 53 27 am](https://user-images.githubusercontent.com/2459524/32283722-8c318bd6-befb-11e7-8300-d99d1240d1b6.png)
![screen shot 2017-11-01 at 11 52 50 am](https://user-images.githubusercontent.com/2459524/32283723-8c424566-befb-11e7-8c3b-d0e292fe7e7c.png)

**Comment by connie-clark** [comment]
This error occurs when the json-text in the comment raises an exception when it is passed to JSON.parse.
From your screenshots - the json looks okay to me.
Try doing a copy-past to json-lint to see what it says == good to do both from the Comments text @ trello, and from the error-alert -- to see if there is any difference.

**Comment by moveair** [comment]
Both came back with a valid responses. I then tried to run the Json export again without success then again without the nickname line and once again the same error turns up

**Comment by connie-clark** [comment]
Turns out there was a typo in my code - which was causing all saved preferences to fail with that 'nickname' error message.

Now fixed - please try it again (your saved preferences should be fine)

**Comment by moveair** [comment]
Awesome!! Works great! except now the print preferences are getting printed. Not really an issue for me but you might want to know

**Comment by connie-clark** [comment]
Fixed. The MY~PRINT~PREFERENCES card is no longer being printed - as you can always view it via Trello.
