### ISSUE TITLE
Printing Out Card Members

### ISSUE THREAD

**Issue by MOTYSHIZ** [connie-clark/print-trello#4]
Hello there, Connie!

Thanks for making such a useful solution for Trello printouts, it's the best I've found so far for our purposes.
We use this to print out progress reports at my workplace.

I was wondering if it was possible to print out card members, so that members could be appropriately credit. If such info is not available in the JSON in the first place, that is unfortunate. 

Thanks again!

**Comment by connie-clark** [comment]
Yes, member information for a card IS included in the JSON.  What options would you want for including the members
- at top of card, or bottom or ...
- what to show for member name - see attached file for available info
- should members be shown in the order trello provides, or alphabetical by name or username ??
[member-info.txt](https://github.com/connie-clark/print-trello/files/1583612/member-info.txt)

**Comment by MOTYSHIZ** [comment]
Oh hi, Connie! 
Sorry for the very slow response. The holidays got the best of me. Thanks for your quick one!
All we would really need is to have the members list printable at the top of the card for the sake of giving credit. Alphabetically could be nice, but it's not a necessity to us.

Thank you so much! Your tool is amazing, and I'm really surprised that your github isn't brimming with follows for this. Hope you had a great holiday season!

**Comment by marcelfp** [comment]
Hello!

Your project is the only way I found to print the boards the way I need. Thank you for your work.
Only information missing is the card members.
If possible, the members could be shown after card name, just as it is for card creator. Also, initials or fullname would be nice. Order could be alphabetically.
Thank you

**Comment by connie-clark** [comment]
Sorry for the delay.

I've just loaded some new code that now supports a preference for showing
card members.

You will need to set this preference, and then try it out.

I do not have examples with card-members, so just faked a few cards in my
testing  Let me know if you see any problems.

**Comment by MOTYSHIZ** [comment]
No worries! Thanks for your continued efforts.
However, we did move on to a different solution. I'm just posting this in case it is helpful to either of you.
It turns out that all the good things for Trello are Google Chrome extensions. TrelloExport actually gives you robust options to export as CSV.
https://chrome.google.com/webstore/detail/trelloexport/kmmnaeamjfdnbhljpedgfchjbkbomahp?hl=en

Print-trello was a good amount of help before, so for that I thank you very much.
